name = "vm-api-worker"
main = "src/index.ts"
compatibility_date = "2024-08-04"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "vm_management"
database_id = "d23cc0b7-9983-419b-a3ea-38f03f2fcff9"

[[queues.producers]]
queue = "vm-task-queue"
binding = "VM_TASK_QUEUE"